"""create watchlist persons table

Revision ID: 10695c73be2b
Revises: 006dc06af198
Create Date: 2026-09-05 09:32:03.058592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10695c73be2b'
down_revision: Union[str, Sequence[str], None] = '006dc06af198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_persons_external_reference'), 'watchlist_persons', ['external_reference'], unique=False)
    op.create_index(op.f('ix_watchlist_persons_id'), 'watchlist_persons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_persons_id'), table_name='watchlist_persons')
    op.drop_index(op.f('ix_watchlist_persons_external_reference'), table_name='watchlist_persons')
    op.drop_table('watchlist_persons')
    # ### end Alembic commands ###