"""create watchlist vehicles table

Revision ID: 6a81579fda10
Revises: 10695c73be2b
Create Date: 2026-09-05 09:36:54.356068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a81579fda10'
down_revision: Union[str, Sequence[str], None] = '10695c73be2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_vehicles_id'), 'watchlist_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_vehicles_plate_number'), 'watchlist_vehicles', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_vehicles_plate_number'), table_name='watchlist_vehicles')
    op.drop_index(op.f('ix_watchlist_vehicles_id'), table_name='watchlist_vehicles')
    op.drop_table('watchlist_vehicles')
    # ### end Alembic commands ###